development:
  adapter: postgresql
  encoding: utf8
  database: merchant_development
  host: localhost
  pool: 5
  username: 
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: merchant_test
  host: localhost
  pool: 5
  username: 
  password:
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: merchant_production
  host: localhost
  pool: 5
  username: 
  password:
  timeout: 5000